name: EconomyEngine
version: '${project.version}'
main: me.wryuin.EconomyEngine
api-version: '1.16'
softdepend: [PlaceholderAPI]
commands:
  economy:
    description: Управление экономикой сервера
    usage: /economy <create/set/add/remove/give/top>
    permission: economyengine.use
    permission-message: У вас нет прав на эту команду!
  economygui:
    description: Open the economy management GUI
    aliases: [ecogui, econgui]
    usage: /economygui
permissions:
  economyengine.use:
    description: Доступ к базовым командам экономики
    default: op
  economyengine.create:
    description: Создание новых валют
    default: op
  economyengine.set:
    description: Установка баланса игрока
    default: op
  economyengine.add:
    description: Добавление баланса игроку
    default: op
  economyengine.remove:
    description: Удаление баланса у игрока
    default: op
  economyengine.give:
    description: Передача валюты другому игроку
    default: true
  economyengine.top:
    description: Просмотр топа богатейших игроков
    default: true
  economyengine.reload:
    description: Reload plugin data
    default: op
  economyengine.admin:
    description: Allows access to all EconomyEngine commands
    default: op
  economyengine.gui:
    description: Allows access to the EconomyEngine GUI
    default: op